### ISSUE TITLE
Any plans to support more languages?

### ISSUE THREAD

**Issue by LinkSake** [nobbmaestro/nvim-andromeda#2]
I really like this color scheme, but it dosen't appear to highlight correctly more languages than python. Se image for a `.lua` example:

![Screenshot 2023-08-23 at 16 23 18](https://github.com/nobbmaestro/nvim-andromeda/assets/24723752/57a8c4ad-83c9-4e34-9750-7ea48c44708b)

Are there plans to support more languages? 
Would love to help providing more languages but, I new to nvim so not sure how the colors are set.

**Comment by nobbmaestro** [comment]
As a matter of fact, this package relies on tree-sitter parsers. Therefore, I suspect that you have not installed any other parser besides for python.

Open the example *.lua file from above in neovim and run following command:
```
:TSInstall lua
```

Once installed, your lua code shall change into this:
<img width="488" alt="image" src="https://github.com/nobbmaestro/nvim-andromeda/assets/77891635/cf706406-ee1b-4068-8580-555609f6aade">

If the above did indeed work, update your tree-sitter config by either:

- adding wanted language parsers into `ensure_installed` list, for instance: 
```lua
ensure_installed = { "python", "c", "lua" },
``` 
- setting auto-install flag, which will install the missing parser automatically when needed, i.e., 
```lua
auto_install = true,
```

Hopefully, you will find this helpful.
