### ISSUE TITLE
The text colors change when the file is opened

### ISSUE THREAD

**Issue by Dishant1804** [nobbmaestro/nvim-andromeda#5]
The text colors change arbitarily when the js,jsx,ts,tsx files are opened, even after keeping the config as default.
the ESmodule does not create this error, already tried by making the file in ESnodule form, still the colors are changing in unxpexcted way

https://github.com/nobbmaestro/nvim-andromeda/assets/115367435/ae0b8c8c-7d21-4dd4-a42f-e47678c62c8b

**Comment by nobbmaestro** [comment]
Unfortunately, I'm not entirely convinced that this issue originates at all from this particular plugin. 

However, my initial suspicion is that tree-sitter may cause the changing colors. Therefore, I would strongly recommend to run `:checkhealth nvim-treesitter`. I would also recommend to update the parsers by simply running `:TSUpdate` or reinstalling the parsers entirely by `:TSUninstall all` followed by `:TSInstall <lang>`. 

The sole purpose of this very plugin is to **map a color to a highlighting group**. It is up to the parser (handled by tree-sitter) to choose correct parser for the buffer.

Please, let me know if this helped you resolving the issue.

**Comment by Dishant1804** [comment]
It doesn't work i tried all the suggestions you have given, 
![Screenshot from 2024-01-07 12-19-39](https://github.com/nobbmaestro/nvim-andromeda/assets/115367435/40140da1-e896-4a41-b173-0f74b91646a5)

moreover i would like to say that i am using eslint is that causing the problem? if yes what is the work around?

**Comment by Dishant1804** [comment]
On further debugging i found out that this originates from `tsserver` lsp. by adding 
`  vim.api.nvim_create_autocmd("LspAttach", {
  callback = function(args)
    local client = vim.lsp.get_client_by_id(args.data.client_id)
    client.server_capabilities.semanticTokensProvider = nil
  end,
});`
in the init.lua fixes this issue of changing colors which was happening due to semanticTokensProvider

**Comment by Dishant1804** [comment]
On further debugging i found out that this originates from `tsserver` lsp. by adding 
`  vim.api.nvim_create_autocmd("LspAttach", {
  callback = function(args)
    local client = vim.lsp.get_client_by_id(args.data.client_id)
    client.server_capabilities.semanticTokensProvider = nil
  end,
});`
in the init.lua fixes this issue of changing colors which was happening due to semanticTokensProvider
